version: "3.7"

services:
    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        expose:
            - "80"
            - "443"
        ports:
            - "80:80"
            - "443:443"
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "service", "nginx", "status"]
            interval: 60s
            timeout: 5s

    chibisafe:
        build:
            context: ../
            dockerfile: ./docker/chibisafe/Dockerfile
        expose:
            - "5000"
            - "5001"
        restart: unless-stopped
        environment:
            OVERWRITE_SETTINGS: "false"
            CHUNK_SIZE: 90
            ROUTE_PREFIX: /api
            RATE_LIMIT_WINDOW: 2
            RATE_LIMIT_MAX: 5
            BLOCKED_EXTENSIONS: ".jar,.exe,.msi,.com,.bat,.cmd,.scr,.ps1,.sh"
            SECRET: ""
            MAX_LINKS_PER_ALBUM: 5
            META_THEME_COLOR: "#20222b"
            META_DESCRIPTION: "Blazing fast file uploader and bunker written in node! ðŸš€"
            META_KEYWORDS: "chibisafe,upload,uploader,file,vue,images,ssr,file uploader,free"
            META_TWITTER_HANDLE: ""
            SERVER_PORT: 5000
            DOMAIN: "http://localhost:5000"
            SERVICE_NAME: chibisafe
            MAX_SIZE: 5000
            GENERATE_THUMBNAILS: "true"
            GENERATE_ZIPS: "true"
            STRIP_EXIF: "true"
            SERVE_WITH_NODE: "true"
            GENERATED_FILENAME_LENGTH: 6
            GENERATED_ALBUM_LENGTH: 4
            PUBLIC_MODE: "false"
            USER_ACCOUNTS: "true"
            ADMIN_ACCOUNT: ""
            ADMIN_PASSWORD: ""
            DB_CLIENT: "sqlite3"
            DB_HOST: ""
            DB_USER: ""
            DB_PASSWORD: ""
            DB_DATABASE: ""
