version: "3.7"

services:
    chibisafe:
        environment:
            CHUNK_SIZE: 90
            SECRET: "wowfcgMHqZHwOIMLadWrKu3liyqPOOILpDLSDvuxq3YGhJmiZXJCVpnF96l11WfR"
            ADMIN_ACCOUNT: "admin"
            ADMIN_PASSWORD: "admin"
            # OVERWRITE_SETTINGS: 'false'
            # ROUTE_PREFIX: /api
            # RATE_LIMIT_WINDOW: 2
            # RATE_LIMIT_MAX: 5
            # BLOCKED_EXTENSIONS: '.jar,.exe,.msi,.com,.bat,.cmd,.scr,.ps1,.sh'
            # META_THEME_COLOR: '#20222b'
            # META_DESCRIPTION: 'Blazing fast file uploader and bunker written in node! ðŸš€'
            # META_KEYWORDS: 'chibisafe,upload,uploader,file,vue,images,ssr,file uploader,free'
            # META_TWITTER_HANDLE: ''
            # SERVER_PORT: 5000
            # DOMAIN: 'http://chibisafe.moe'
            # SERVICE_NAME: chibisafe
            # MAX_SIZE: 5000
            # GENERATE_THUMBNAILS: 'true'
            # GENERATE_ZIPS: 'true'
            # STRIP_EXIF: 'true'
            # SERVE_WITH_NODE: 'true'
            # GENERATED_FILENAME_LENGTH: 6
            # GENERATED_ALBUM_LENGTH: 4
            # PUBLIC_MODE: 'false'
            # USER_ACCOUNTS: 'true'
            # DB_CLIENT: 'sqlite3'
            # DB_HOST: ''
            # DB_USER: ''
            # DB_PASSWORD: ''
            # DB_DATABASE: ''
